apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticweb
  labels:
    app: staticweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staticweb
  template:
    metadata:
      labels:
        app: staticweb
    spec:
      containers:
      - name: staticweb
        image: neehar2601/staticweb:v1
        ports:
        - containerPort: 80
