apiVersion: v1
kind: Service
metadata:
  name: staticweb
  labels:
    app: staticweb
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: staticweb
